[project]
name = "kitab-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pipreqs>=0.5.0",
    "nltk==3.9.1",
    "torchmetrics==1.6.1",
    "openai==1.61.1",
    "paddleocr>=2.0.1",
    "python-Levenshtein==0.26.1",
    "sacrebleu==2.5.1",
    "datasets==3.2.0",
    "google-genai==1.0.0",
    "surya-ocr==0.11.0",
    "qwen-vl-utils==0.0.10",
    "accelerate==1.4.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "transformers==4.49.0",
    "regex==2024.11.6",
    "easyocr==1.7.2",
    "pytesseract==0.3.13",
    "doclayout_yolo==0.0.3",
    "huggingface_hub==0.26.2",
    "matplotlib==3.10.0",
    "numpy==2.2.2",
    "pillow==10.4.0",
    "python-dotenv==1.0.1",
    "tqdm==4.66.6",
    "pdf2image==1.17.0",
    "marker-pdf==1.4.0",
    "docling==2.21.0",
]
